[project]
name = "codeflash"
dynamic = ["version"]
description = "Client for codeflash.ai - automatic code performance optimization, powered by AI"
authors = [{ name = "CodeFlash Inc.", email = "contact@codeflash.ai" }]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "BSL-1.1" }
keywords = [
    "codeflash",
    "performance",
    "optimization",
    "ai",
    "code",
    "machine learning",
    "LLM",
]
dependencies = [
    "unidiff>=0.7.4",
    "pytest>=7.0.0",
    "gitpython>=3.1.31",
    "libcst>=1.0.1",
    "jedi>=0.19.1",
    "pytest-timeout>=2.1.0",
    "tomlkit>=0.11.7",
    "junitparser>=3.1.0",
    "pydantic>=1.10.1",
    "isort>=5.11.0",
    "dill>=0.3.8",
    "lxml>=5.3.0",
    "tabulate[widechars]>=0.9.0",
    "crosshair-tool>=0.0.78",
    "coverage>=7.6.4",
    "line_profiler>=4.2.0",
    "platformdirs>=4.3.7",
    "requests>=2.28.0",
    "codeflash-benchmark",
    "pytest-asyncio>=1.2.0",
]

[tool.codeflash]
# All paths are relative to this pyproject.toml's directory.
module-root = "src/codeflash"
tests-root = "tests"
ignore-paths = []

formatter-cmds = ["disabled"]

[tool.pytest.ini_options]
filterwarnings = ["ignore::pytest.PytestCollectionWarning"]
markers = ["ci_skip: mark test to skip in CI environment"]
norecursedirs = ["tests/code_to_optimize"]
pythonpath = ["."]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/codeflash"]

[tool.hatch.build.hooks.version]
path = "src/codeflash/version.py"
template = """# These version placeholders will be replaced by uv-dynamic-versioning during build.
__version__ = "{version}"
"""

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
codeflash-benchmark = { workspace = true }

[tool.uv-dynamic-versioning]
enable = true
style = "pep440"
vcs = "git"

[dependency-groups]
dev = ["ruff", { include-group = "test" }]
test = [
    "black",
    "jax",
    "numpy",
    "pandas",
    "pyrsistent",
    "scipy",
    "sqlalchemy",
    "tensorflow",
    "torch",
    "xarray",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"
