"""Re-exports from sub-modules for backward compatibility.

All model classes now live in:
  - codeflash.models.api      — API request/response DTOs
  - codeflash.models.domain   — Core domain models
  - codeflash.models.coverage — Coverage and benchmark types
"""

from codeflash.models.api import (
    AIServiceAdaptiveOptimizeRequest,
    AIServiceCodeRepairRequest,
    AIServiceRefinerRequest,
    AdaptiveOptimizedCandidate,
    CoverReturnCode,
    OptimizationReviewResult,
    OptimizedCandidateSource,
    TestDiff,
    TestDiffScope,
)
from codeflash.models.coverage import (
    BenchmarkDetail,
    BenchmarkKey,
    CoverageData,
    CoverageStatus,
    FunctionCoverage,
    ProcessedBenchmarkInfo,
    TestingMode,
)
from codeflash.models.domain import (
    BestOptimization,
    CandidateEvaluationContext,
    CodeContextType,
    CodeOptimizationContext,
    CodePosition,
    CodeString,
    CodeStringsMarkdown,
    ExperimentMetadata,
    FunctionCalledInTest,
    FunctionParent,
    FunctionSource,
    FunctionTestInvocation,
    GeneratedTests,
    GeneratedTestsList,
    InvocationId,
    OptimizedCandidate,
    OptimizedCandidateResult,
    OptimizationSet,
    OriginalCodeBaseline,
    TestFile,
    TestFiles,
    TestResults,
    TestsInFile,
    ValidCode,
)

__all__ = [
    "AIServiceAdaptiveOptimizeRequest",
    "AIServiceCodeRepairRequest",
    "AIServiceRefinerRequest",
    "AdaptiveOptimizedCandidate",
    "BenchmarkDetail",
    "BenchmarkKey",
    "BestOptimization",
    "CandidateEvaluationContext",
    "CodeContextType",
    "CodeOptimizationContext",
    "CodePosition",
    "CodeString",
    "CodeStringsMarkdown",
    "CoverReturnCode",
    "CoverageData",
    "CoverageStatus",
    "ExperimentMetadata",
    "FunctionCalledInTest",
    "FunctionCoverage",
    "FunctionParent",
    "FunctionSource",
    "FunctionTestInvocation",
    "GeneratedTests",
    "GeneratedTestsList",
    "InvocationId",
    "OptimizationReviewResult",
    "OptimizationSet",
    "OptimizedCandidate",
    "OptimizedCandidateResult",
    "OptimizedCandidateSource",
    "OriginalCodeBaseline",
    "ProcessedBenchmarkInfo",
    "TestDiff",
    "TestDiffScope",
    "TestFile",
    "TestFiles",
    "TestResults",
    "TestsInFile",
    "TestingMode",
    "ValidCode",
]
